align footer width to body width
incubateur-ademe/quefairedemesdechets pull request #91
Opened 2024-06-25 16:16 UTC by kolok

![CleanShot 2024-06-25 at 18 16 02](https://github.com/incubateur-ademe/quefairedemesdechets/assets/454431/b01d2a19-e114-4402-9efe-eb5a2e6e3754)

2024-06-26 13:05 UTC, fabienheureux reviewed
Je ne sais pas si on va maintenir ce code longtemps mais je serais tenté d'en faire une variable dans le thème styled-components. 

Tu penses que dans six mois / un an cette code base vivra toujours ou non ?

2024-06-26 14:00 UTC, kolok commented
> Je ne sais pas si on va maintenir ce code longtemps mais je serais tenté d'en faire une variable dans le thème styled-components.
> 
> Tu penses que dans six mois / un an cette code base vivra toujours ou non ?
> 
> Genre par ici https://github.com/incubateur-ademe/quefairedemesdechets/blob/master/src/utils/styles.js#L5

Oui tu as raison
Est-ce que tu peux prendre la suite pour l'implémenter ?

2024-08-13 07:46 UTC, kolok commented on src/utils/styles.js
> +      max_width_with_gutters: "58.75rem",
Je ne sais pas si le nom est bien choisit mai je n'ai pas eu d'inspiration :)

2024-08-13 11:39 UTC, fabienheureux commented on src/utils/styles.js
> +      max_width_with_gutters: "58.75rem",
Ça me va, est-ce qu'on peut juste utiliser du camelCase ?

2024-08-13 11:46 UTC, fabienheureux requested changes

2024-08-13 11:46 UTC, fabienheureux commented on src/utils/styles.js
> +      max_width_with_gutters: "58.75rem",
```suggestion
      maxWidthWithGutters: "58.75rem",
```

2024-08-13 11:46 UTC, fabienheureux commented on src/components/layout/Web.js
> +  width: ${(props) => props.theme.widths.max_width_with_gutters};
```suggestion
  width: ${(props) => props.theme.widths.maxWidthWithGutters};
```

2024-08-13 11:46 UTC, fabienheureux commented on src/components/layout/IframeFooter.js
> +  max-width: ${(props) => props.theme.widths.max_width_with_gutters};
```suggestion
  max-width: ${(props) => props.theme.widths.maxWidthWithGutters};
```

2024-08-13 11:46 UTC, fabienheureux commented on src/components/layout/Footer.js
> +  max-width: ${(props) => props.width || props.theme.widths.max_width_with_gutters};
```suggestion
  max-width: ${(props) => props.width || props.theme.widths.maxWidthWithGutters};
```

2024-08-21 17:50 UTC, fabienheureux approved these changes
Oops désolé j'aurais pu tout à fait prendre la suite 

Ok pour moi !

2024-09-06 17:55 UTC, fabienheureux approved these changes

2024-09-09 12:23 UTC, merged